Add thumb position on storefront
vtex-apps/product-details pull request #105
Opened 2019-04-05 19:15 UTC by theomoura

#### What is the purpose of this pull request? #### What problem is this solving?

Add the customization to the thumbnails image position on the storefront.

#### How should this be manually tested?

[Access](https://imageposition--storecomponents.myvtex.com/admin/cms/storefront); enter on a product with thumbnails; Go to product details section and change "Thumbnails position"

#### Types of changes

* [ ] Bug fix (a non-breaking change which fixes an issue)
* [x] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

2019-04-05 19:38 UTC, rerissondaniel requested changes
Missing CHANGELOG.md
Also, not directly related to this PR, but should there be a `below` option, as described [here](https://github.com/vtex-apps/store-components/issues/359).

2019-04-05 20:17 UTC, rerissondaniel approved these changes

2019-04-05 22:24 UTC, JuanAlmeida12 approved these changes

2019-04-06 14:15 UTC, matheusps approved these changes
Just personal preferences, change it if you feel like it 😬

2019-04-06 14:15 UTC, matheusps commented on react/utils/thumbnailPositionEnum.js
> +export function getThumbnailsPositionNames() {
You could do like:
```suggestion
export const getThumbnailsPositionNames = () =>
```

2019-04-06 14:15 UTC, matheusps commented on react/utils/thumbnailPositionEnum.js
> +export function getThumbnailsPositionValues() {
Here too 🤓

2019-04-08 12:26 UTC, ArthurSampaio approved these changes

2019-04-08 17:31 UTC, merged