Fix/heart position size wish list
vtex-apps/product-details pull request #118
Opened 2019-05-08 19:10 UTC by ThaynanAndrey

#### What is the purpose of this pull request?

Fix heart's position and size, and align products menu's button.

#### What problem is this solving?

The heart's position and size doesn't according expected template. Besides that, the products menu's button isn't aligned with products list.

#### How should this be manually tested?

1. Acess this [workspace](https://thaynan--storecomponents.myvtex.com/);
2. Selects a listed product on home page that contains more one image;
3. Observes that the heart's position isn't over image, but over small images;
Besides, observes that heart size is 16x16 px, when in fact it should be 32x32.

#### Types of changes

* [X] Bug fix (a non-breaking change which fixes an issue)
* [ ] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

2019-05-08 19:34 UTC, klzns requested changes
Do not remove yarn.lock

2019-05-08 19:39 UTC, GustavoMA commented
Your yarn deleted all `integrity sha512` checks. Check out your yarn version.

2019-05-08 19:44 UTC, lucis approved these changes
Check if everything is fine with the `yarn.lock`, probably is!

Nice job ;)

2019-05-08 19:44 UTC, luciannojunior commented on react/ProductDetails.js
> +    const classAddonDetails = classNames('absolute z-3 left-0', {
```suggestion
    const addonDetailsClasses = classNames('absolute z-3 left-0', {
```

2019-05-08 19:44 UTC, klzns approved these changes

2019-05-08 20:19 UTC, oldufre requested changes
O alinhamento e a distância tá errado, tá mais para cima do que para baixo Tem um padding de 4 e 12 a mais. Acho que isso que ta deixando a distancia errada.
São 2rem de distância da esquerda para direita e 2rem de distancia de cima para baixo.

![image](https://user-images.githubusercontent.com/29896547/57405651-5f18f080-71b5-11e9-8870-4080e1d96d5c.png)

2019-05-08 20:40 UTC, vitoria approved these changes
Very good! :clap:

2019-05-09 17:32 UTC, oldufre approved these changes

2019-05-09 17:49 UTC, GustavoMA approved these changes

2019-05-09 20:16 UTC, merged