Feature/product specifications
vtex-apps/product-details pull request #119
Opened 2019-05-08 20:06 UTC by ArthurSampaio

#### What is the purpose of this pull request?

Enable ProductSpecifications configuration from Storefront/CSM

#### How should this be manually tested?
Acess the follow [ws ](https://specificationproduct--storecomponents.myvtex.com/admin/cms/storefront)and search for shirt product. After this, you should play with the ProductDetails schema.

#### Screenshots or example usage

![highlightspec](https://user-images.githubusercontent.com/17649410/57404872-72c35780-71b3-11e9-8efa-35a16dea0b55.gif)

#### Types of changes

* [x] Bug fix (a non-breaking change which fixes an issue)
* [x] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

2019-05-08 21:20 UTC, kevinch requested changes

2019-05-08 21:20 UTC, kevinch commented on CHANGELOG.md
> +- Readded `Product-Specifications` configuration throught CMS
Remove "Readded" verb since it's already in the section "Added".

2019-05-08 21:20 UTC, kevinch commented on react/ProductDetails.js
> +          x => x.name.toLowerCase() === item.trim().toLowerCase()
Use a more descriptive variable name.

2019-05-09 17:56 UTC, kevinch approved these changes

2019-05-10 11:55 UTC, salesfelipe requested changes

2019-05-10 11:55 UTC, salesfelipe commented on react/ProductDetails.js
> +        $ref: '#/definitions/specificationsDefault',
This file is way too big, maybe you can extract parts of it to aux files

2019-05-10 17:10 UTC, salesfelipe approved these changes

2019-05-13 17:56 UTC, lbebber requested changes
Just needs a small help text beside the "Type specifications" input (as well as copy adjustments, which can be done later)

2019-05-27 18:26 UTC, lbebber approved these changes

2019-05-27 18:26 UTC, merged