Show the heart icon of wish list in product details
vtex-apps/product-details pull request #128
Opened 2019-06-11 19:30 UTC by ThaynanAndrey

#### What is the purpose of this pull request?

Show the heart icon of wish list in product details.

#### What problem is this solving?

In product details screen doesn't show the heart icon to add product in wish list.

#### Screenshots or example usage

#### Types of changes

* [X] Bug fix (a non-breaking change which fixes an issue)
* [ ] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

2019-06-11 19:38 UTC, klzns requested changes

2019-06-11 19:38 UTC, klzns commented on react/AddonWrapper.js
> +        quantity: 1,
Set your indent to 2 spaces, currently it's using 4

2019-06-11 19:38 UTC, klzns commented on react/AddonWrapper.js
> +        productId: path(['product', 'productId'], valuesFromContext)
Check the code of:
https://github.com/vtex-apps/product-summary/pull/164/files

You're creating a new `product` object in every render.

2019-06-11 19:38 UTC, klzns commented on react/AddonWrapper.js
> +    const isMoreThanOneImage = () => {
Use variable instead of function

2019-06-11 19:38 UTC, klzns commented on react/ProductDetails.js
> +                    <ExtensionPoint
Why this changed?

2019-06-11 19:38 UTC, klzns commented on store/interfaces.json
> +  "product-addon-wrapper": {
Use a more descriptive name 

`product-add-to-list-button` or something like that

2019-06-11 19:38 UTC, klzns commented on store/interfaces.json
> +    "component": "AddonWrapper",
Same

2019-06-11 21:28 UTC, klzns approved these changes

2019-06-12 11:37 UTC, lucasecdb commented on react/ProductDetails.js
> -                      <ExtensionPoint
shouldn't you still have this? for backwards compatibility

2019-06-12 12:07 UTC, klzns requested changes

2019-06-12 12:07 UTC, klzns commented on react/ProductDetails.js
> +                    <ExtensionPoint
Ops, you should keep the div

2019-06-12 12:53 UTC, lucasecdb commented on react/ProductDetails.js
> -                        large={!mobile}
you should also keep the props, else the button won't work

2019-06-12 13:00 UTC, lucasecdb approved these changes

2019-06-12 13:14 UTC, klzns approved these changes

2019-06-12 17:31 UTC, merged