Passing ean info to ProductName
vtex-apps/product-details pull request #27
Opened 2018-05-29 21:54 UTC by salesfelipe

#### What is the purpose of this pull request?
Add product's EAN info

#### What problem is this solving?

Giving more information to the user

#### How should this be manually tested?

[workspace](https://pname--storecomponents.myvtex.com/google-pixel2/p)

#### Screenshots or example usage

![image](https://user-images.githubusercontent.com/3926634/40687596-9aa1c5c6-6371-11e8-8e60-b14011cc9ff1.png)

#### Types of changes

* [ ] Bug fix (a non-breaking change which fixes an issue)
* [X] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

2018-05-30 13:10 UTC, andreldsa approved these changes

2018-06-01 12:23 UTC, brunojdo requested changes
I'm not sure if this is the right property to show. EAN is a sku prop.

2018-06-01 14:00 UTC, andreldsa approved these changes

2018-06-04 21:56 UTC, brunojdo approved these changes

2018-06-04 21:56 UTC, merged