WIP: Add divided Content Loader logic
vtex-apps/product-details pull request #45
Opened 2018-07-26 18:57 UTC by estacioneto

#### What is the purpose of this pull request?

Remove the single content loader to show data that is already available.

#### What problem is this solving?

A single content loader is shown, but some product information is cached.

#### How should this be manually tested?

[Access the workspace](https://estacio--storecomponents.myvtex.com/motorola-moto-x4/p)

#### Screenshots or example usage
![image](https://user-images.githubusercontent.com/15948386/43282424-7f5e1ab4-90ec-11e8-94bb-738d0d466c1b.png)

#### Types of changes

* [ ] Bug fix (a non-breaking change which fixes an issue)
* [x] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

2018-07-26 19:23 UTC, brunojdo approved these changes

2018-07-30 13:40 UTC, claudivanfilho requested changes
CHANGELOG

2018-07-30 14:20 UTC, claudivanfilho approved these changes

2018-07-31 16:52 UTC, brunojdo approved these changes

2018-07-31 19:47 UTC, andreldsa approved these changes

2018-08-01 14:53 UTC, merged