[WIP] Add tabs view mode to Product specifications
vtex-apps/product-details pull request #84
Opened 2019-02-11 19:57 UTC by paul0vinicius

#### What is the purpose of this pull request?

#### What problem is this solving?

#### How should this be manually tested?

#### Screenshots or example usage

#### Types of changes

* [ ] Bug fix (a non-breaking change which fixes an issue)
* [x] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

2019-02-11 20:02 UTC, brunojdo requested changes

2019-02-11 20:02 UTC, brunojdo commented on react/ProductDetails.js
> +                <div className={`pv2 w-100 mt8 h-100 ${productSpecificationsTabsMode ? 'w-100' : 'w-60'}`}>
remove the first w-100

2019-02-11 20:02 UTC, brunojdo commented on react/ProductDetails.js
> +                <div className={`pv2 mt8 h-100 ${productSpecificationsTabsMode ? 'w-100' : 'w-40'}`}>
showSpecificationTabs

2019-02-11 21:48 UTC, brunojdo approved these changes

2019-02-12 13:05 UTC, theomoura approved these changes

2019-02-12 13:52 UTC, merged