Refactoring Product Details to use hooks and avoid unnecessary rerender.
vtex-apps/product-details pull request #97
Opened 2019-03-27 15:09 UTC by JuanAlmeida12

#### What is the purpose of this pull request?

As the title says.

#### How should this be manually tested?

[Access this workspace](https://blurredimage--storecomponents.myvtex.com)

#### Types of changes

* [ ] Bug fix (a non-breaking change which fixes an issue)
* [ ] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

2019-03-27 15:15 UTC, jgfidelis commented
Can't  you hold a reference to selectedItem instead of calling it 999 times on `render`
Like:
```
const selectedItem = getSelectedItem()
...
replace all selectedItem() to selectedItem
```

2019-03-27 16:57 UTC, theomoura approved these changes

2019-03-27 17:30 UTC, GustavoMA requested changes

2019-03-27 17:30 UTC, GustavoMA commented on react/ProductDetails.js
> +import { ExtensionPoint, useRuntime } from 'vtex.render-runtime'
You need to create the mock of `useRuntime`. The tests are failing because of that.

2019-03-27 18:15 UTC, matheusps commented on react/ProductDetails.js
> +  const selectedItem = useCallback(() => {
I think `useMemo` would be a better fit.

2019-03-27 18:15 UTC, matheusps commented on react/ProductDetails.js
> +  const commertialOffer = useCallback(() => {
Same

2019-03-27 18:15 UTC, matheusps commented on react/ProductDetails.js
> +  const sellerId = useCallback(() => {
Same 🤓

2019-03-27 18:15 UTC, matheusps commented on react/ProductDetails.js
> +  const getImages = useCallback(() => {
Here as well

2019-03-27 18:15 UTC, matheusps commented on react/ProductDetails.js
> +    skuItems: selectedItem() &&
The change to memo would make this look better too.

2019-03-27 18:15 UTC, matheusps commented on react/ProductDetails.js
> +                  <ExtensionPoint id="product-images" images={getImages()} />
Do not call functions like that on component props. Could cause undesired effects.

2019-03-27 19:18 UTC, GustavoMA approved these changes

2019-03-28 15:36 UTC, matheusps approved these changes

2020-04-24 14:58 UTC, victorhmp commented
Closing this since it became stale.

2020-04-24 14:58 UTC, closed without merging